---
title: "Use_Flextable"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Use_Flextable}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width=10, 
  fig.height=6
)
```

## Introduction

This document is designed to provide you with practical examples of how to use `headr` to add headers and footnotes to your TFL outputs.

Here's an example of using `headr` with `Flextable` to generate table outputs:

```{r setup}
# Load the necessary libraries
library(headr)
library(flextable)
#library(tables)
library(palmerpenguins)
library(magrittr)
library(glue)
library(dplyr)
# (to use |> version 4.1.0 of R is required, for lower versions we recommend %>% from magrittr)
 

ft_pen <- penguins |> 
  select(species, island, ends_with("mm")) |> 
  group_by(species, island) |> 
  summarise(
    across(
      where(is.numeric), 
      .fns = list(
        avg = ~ mean(.x, na.rm = TRUE),
        sd = ~ sd(.x, na.rm = TRUE)
      )
    ),
    .groups = "drop") |> 
  rename_with(~ tolower(gsub("_mm_", "_", .x, fixed = TRUE))) |> 
  flextable() |> 
  colformat_double() |>
  separate_header() |> 
  theme_vanilla() |> 
  align(align = "center", part = "all") |>
  valign(valign = "center", part = "header") |> 
  autofit()

ft_pen <- labelizor(
  x = ft_pen, 
  part = "header", 
  labels = c("avg" = "Mean", "sd" = "Standard Deviation"))

ft_pen <- labelizor(
  x = ft_pen, 
  part = "header", 
  labels = stringr::str_to_title)

## Title and footnote spreadsheet path and filename
fname <- "C:/Users/u066227/Rproj/sample_titles.xls"
# hfooter_file <- read_footer("C:/Users/u066227/Rproj/sample_titles.xls")
# hfooter_list <- select_with_number(df =hfooter_file,  tnumber = "Table 2.1")
# 
# head_list <- ht_list %>% select(starts_with("TTL"), POPULATION) 
# head_list <- Filter(function(x) !is.na(x), head_list)
# foot_list <- ht_list %>% select(starts_with("FOOT")) 

## Obtain header (title, subtitle, population) with one functional call
head_list <- header_for_flextable(filename = fname, tnumber = "Table 2.1")

## Obtain footnotes and ref notes (including program name, run timestamp, data sources) with one functional call
foot_list <- footer_for_flextable(filename = fname, tnumber = "Table 2.1")


ft <- footnote( ft_pen, i = 1, j = 1:2,
                value = as_paragraph(
                  unlist(foot_list)
                ),
                ref_symbols = c(" ", " "),
                part = "header",inline=FALSE) %>% 
                # set_caption(caption = {paste(head_list, sep = "\n", collapse = " \n ")}, 
                # style = "Table Caption")#, 
  #autonum = run_autonum(seq_id = "tab", bkm = "tab1"))
# ft <- footnote( ft, i = 1, j = 3:4,
#                 value = as_paragraph(
#                   c("This is footnote three",
#                     "This is footnote four")
#                 ),
#                 ref_symbols = c( "c","d"),
#                 part = "header",inline=T)

  add_header_lines(values = {paste(head_list, sep = "\n", collapse = " \n ")}, top = TRUE)
  # values = c("this is a first line", 
  #    "this is a second line") ) 

#ft <- hline_bottom(ft, j = NULL, border = NULL, part = "header")

ft <- add_footer_lines(ft, values = glue("Generated from {basename(rstudioapi::getSourceEditorContext()$path)} on {Sys.time()} Data Source(s): ADSL\n"))
```

## Examples

### Simple Examples

#### Simple Layout with margins

In these examples, we're creating a table with 'flextable\` package.

#### `show(layout)` method:
